services:
  web:
    build: .
    ports:
      - "8000:8000"
    privileged: true

  db:
    image: postgres
    environment:
      - POSTGRES_USER = user
      - POSTGRES_PASSWORD = 123
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB  =  db
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
    dbdata: