# Generated by Django 5.1.2 on 2024-12-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_customer_shopaddress_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopaddress',
            options={'ordering': ('address',), 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
    ]
